apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: socialz-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: socialz-app-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60