apiVersion: v1
kind: Service
metadata:
  name: socialz-service
  labels:
    name: socialz-service
    app: socialz-app
spec:
  type: LoadBalancer
  ports:
   - port: 80
     targetPort: 3000
  selector:
    name: socialz-app-pod
    app: socialz-app