default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: SocialZ_development

test:
  <<: *default
  database: SocialZ_test

production:
  <<: *default
  database: SocialZ_production
  username: postgres
  password: <%= ENV['SOCIALZ_DATABASE_PASSWORD'] %>
